---
version: 2
jobs:
  safety_check:
    machine: true
    working_directory: ~/securedrop.org
    steps:
      - checkout

      - run:
          name: Install testing pre-reqs
          command: |
            virtualenv ~/.venv
            . ~/.venv/bin/activate
            pip install -r devops/requirements.txt

      - run:
          name: Check Python dependencies for CVEs
          command: |
            . ~/.venv/bin/activate
            make safety

      - run:
          name: Static code analysis for vulnerabilities
          command: |
            make bandit

  build:
    machine: true
    working_directory: ~/securedrop.org
    steps:
      - checkout

      - run:
          name: Install testing pre-reqs
          command: |
            virtualenv ~/.venv
            . ~/.venv/bin/activate
            pip install -r devops/requirements.txt

      - run:
          name: Flake8 linting
          command: |
            make flake8

      - run:
          name: Ensure Django service stands up
          command: |
            . ~/.venv/bin/activate
            make ci-go

      - store_test_results:
          path: ~/securedrop.org/test-results

workflows:
  version: 2
  freedomdotpress_ci:
    jobs:
      - safety_check
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - safety_check
