---
version: 2
jobs:
  safety_check:
    machine: true
    working_directory: ~/securedrop.org
    steps:
      - checkout

      - run:
          name: Install testing pre-reqs
          command: |
            # Set python to 3.5.2
            pyenv global 3.5.2
            pip install -U pip
            pip install pipenv
            pipenv install

      - run:
          name: Check Python dependencies for CVEs
          command: |
            pipenv install --selective-upgrade safety
            pipenv run make safety

      - run:
          name: Static code analysis for vulnerabilities
          command: |
            pipenv install --selective-upgrade bandit
            pipenv run make bandit

  npm_audit:
    machine: true
    working_directory: ~/freedom.press
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            # Set to native py3 on circleci image
            pyenv global 3.5.2
            pip install -U pip
            pip install pipenv
            pipenv install
      - run:
          name: Check node dependencies for vulnerabilities
          command: |
            pipenv run make dev-init
            pipenv run make ci-npm-audit
      - store_test_results:
          path: ~/freedom.press/test-results/

  build:
    machine: true
    working_directory: ~/securedrop.org
    steps:
      - checkout

      - run:
          name: Install testing pre-reqs
          command: |
            # Set python to 3.5.2
            pyenv global 3.5.2
            pip install -U pip
            pip install pipenv
            pipenv install

      - run:
          name: Flake8 linting
          command: |
            make flake8

      - run:
          name: BUILD and push containers
          command: |
            pipenv run docker-compose -f prod-docker-compose.yaml build django
            docker login -u "${QUAY_USER}" -p "${QUAY_PASS}" quay.io || true
            make prod-push || true

      - run:
          name: Ensure we can run prod env
          command: |
            pipenv run docker-compose -f prod-docker-compose.yaml up -d
            while ! curl --output /dev/null --silent --head --fail http://localhost:8080; do sleep 1 && echo -n .; done;
            pipenv run docker-compose -f prod-docker-compose.yaml exec django /bin/bash -c "./manage.py test --noinput -k"
            pipenv run docker-compose -f prod-docker-compose.yaml exec django /bin/bash -c "./manage.py makemigrations --dry-run --check"

      - store_test_results:
          path: ~/securedrop.org/test-results

workflows:
  version: 2
  freedomdotpress_ci:
    jobs:
      - safety_check
      - npm_audit
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - safety_check
