---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: local_dev
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: dev
  converge_sequence:
    - converge
    - verify
verifier:
  name: testinfra
  directory: ../shared_tests
  options:
    connection: docker
    hosts: sd_django
  env:
    PSHTT_LOCATION: /usr/local/bin/pshtt
  lint:
    name: flake8
